### ISSUE TITLE
请问如何部署？

### ISSUE THREAD

**Issue by ssln5014** [s0urcelab/serverless-cloud-notepad#16]
按文档报错
```
  pwsh  npm run publish

> serverless-cloud-notepad@1.0.0 publish
> wrangler publish

Proxy environment variables detected. We'll use your proxy for fetch requests.

 ⛅️ wrangler 3.60.3
-------------------

▲ [WARNING] `wrangler publish` is deprecated and will be removed in the next major version.

  Please use `wrangler deploy` instead, which accepts exactly the same arguments.


Total Upload: 39.15 KiB / gzip: 11.42 KiB
Your worker has access to the following bindings:
- KV Namespaces:
  - NOTES: 82faa7b7043c4a04b0db7cae1fea637b
  - SHARE: da3d6dc4a5874f5a8229327d9aa9d11d

✘ [ERROR] A request to the Cloudflare API (/accounts/5af061ede7b10b1738bd475c1bc74a97/workers/scripts/cloud-notepad) failed.

  Uncaught ReferenceError: SCN_SALT is not defined
    at null.<anonymous> (file:///E:/gh/serverless-cloud-notepad/src/constant.js:5:21)
    at null.<anonymous> (worker.js:921:3)
   [code: 10021]


  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/workers-sdk/issues/new/choose
```

**Comment by s0urcelab** [comment]
正在接入github actions自动部署，文档还没更新，预计明天施工完毕

**Comment by ssln5014** [comment]
> src/constant.js 中，把第5行，第7行的variable value改为string // server side salt export const SALT = 'SCN_SALT' // server side secret export const SECRET = 'SCN_SECRET' 内容可以自己修改


这回对了，感谢！

**Comment by s0urcelab** [comment]
@ssln5014 现在可以一键部署了，文档里使用说明已更新，欢迎体验

**Comment by ssln5014** [comment]
> @ssln5014 现在可以一键部署了，文档里使用说明已更新，欢迎体验

好用，爱用，大佬nb
