### ISSUE TITLE
Unexpected fields found in top-level field: "SCN_SALT"

### ISSUE THREAD

**Issue by wfxu** [s0urcelab/serverless-cloud-notepad#17]
```
 [WARNING] Processing wrangler.toml configuration:

    - Unexpected fields found in top-level field: "SCN_SALT"


Attempting to login via OAuth...
F:\js\serverless-cloud-notepad\node_modules\wrangler\wrangler-dist\cli.js:16259
            throw ex;
            ^

SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
    at JSON.parse (<anonymous>)
    at Response.json (F:\js\serverless-cloud-notepad\node_modules\wrangler\wrangler-dist\cli.js:72475:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async exchangeAuthCodeForAccessToken (F:\js\serverless-cloud-notepad\node_modules\wrangler\wrangler-dist\cli.js:105671:23)
    at async Server.<anonymous> (F:\js\serverless-cloud-notepad\node_modules\wrangler\wrangler-dist\cli.js:105807:30)

Node.js v20.10.0
```
这是个什么问题，我搞不懂。

**Comment by s0urcelab** [comment]
为了简化部署流程，接入了Github Actions，这是之前调试代码的问题，可以按照readme说明重新部署试试
